In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [1]:
print(1+1)

2

In [ ]:
df = pd.read_excel("/content/Data Mahasiswa Lulusan Terisi 1.xlsx")

In [ ]:
df

,NIM (Nomor Induk Mahasiswa),Kode Dosen,Kelas,Program Studi,Status Mahasiswa,IPK,SKS Lulus,Tanggal Masuk,Tanggal Keluar,Total Semester,...,IPK Semester 5,IPK Semester 6,IPK Semester 7,IPK Semester 8,IPK Semester 9,IPK Semester 10,IPK Semester 11,IPK Semester 12,IPK Semester 13,IPK Semester 14
0,21110035,ARI,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.57,148,01-AUG-21,2025-02-14,7,...,3.43,3.85,3.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21110034,ARI,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.82,147,01-AUG-21,2025-02-14,7,...,3.83,3.92,3.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21110033,ARI,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.70,153,01-AUG-21,2025-02-14,7,...,3.76,3.68,3.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21110031,ARI,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.81,153,01-AUG-21,2025-02-14,7,...,3.93,3.82,3.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21110029,ARI,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.72,151,01-AUG-21,2025-02-14,7,...,3.85,3.85,3.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,21110028,ARI,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.72,144,01-AUG-21,2025-02-14,7,...,3.87,3.74,3.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,21110021,ARI,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.78,147,01-AUG-21,2025-02-14,7,...,3.96,3.95,3.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,21110018,ARI,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.63,147,01-AUG-21,2025-02-14,7,...,3.73,3.83,3.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,21110014,SIK,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.58,148,01-AUG-21,2025-02-14,7,...,3.23,3.65,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,21110010,SIK,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.88,147,01-AUG-21,2025-02-14,7,...,3.93,3.98,3.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,21110008,SIK,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.98,151,01-AUG-21,2025-02-14,7,...,3.93,4.00,3.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,21110006,SIK,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.85,151,01-AUG-21,2025-02-14,7,...,3.87,3.85,3.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,21110003,SIK,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.70,150,01-AUG-21,2025-02-14,7,...,3.74,3.87,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,21110002,SIK,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.90,148,01-AUG-21,2025-02-14,7,...,3.93,4.00,3.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,21110001,SIK,S1SD-02-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.97,150,01-AUG-21,2025-02-14,7,...,4.00,4.00,3.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,20110033,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.60,146,01-AUG-20,2024-10-17,9,...,3.71,3.67,3.54,3.00,3.00,NaN,NaN,NaN,NaN,NaN
16,20110031,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.87,145,01-AUG-20,2024-02-02,7,...,3.88,3.98,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,20110029,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.55,154,01-AUG-20,2025-02-14,9,...,3.37,3.18,3.73,0.00,3.86,NaN,NaN,NaN,NaN,NaN
18,20110028,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.49,146,01-AUG-20,2024-10-17,9,...,3.20,3.26,3.88,4.00,4.00,NaN,NaN,NaN,NaN,NaN
19,20110027,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,2.93,147,01-AUG-20,2025-02-14,9,...,2.88,2.13,2.81,1.27,2.73,NaN,NaN,NaN,NaN,NaN
20,20110025,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.81,145,01-AUG-20,2024-10-17,9,...,3.75,3.98,3.31,4.00,4.00,NaN,NaN,NaN,NaN,NaN
21,20110024,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.89,144,01-AUG-20,2024-10-17,9,...,3.76,3.70,3.88,4.00,4.00,NaN,NaN,NaN,NaN,NaN
22,20110023,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.57,146,01-AUG-20,2024-10-17,9,...,3.50,3.28,3.79,3.00,3.00,NaN,NaN,NaN,NaN,NaN
23,20110022,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.90,146,01-AUG-20,2024-10-17,9,...,3.83,3.43,4.00,3.50,3.50,NaN,NaN,NaN,NaN,NaN
24,20110019,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.85,145,01-AUG-20,2024-10-17,9,...,3.59,3.90,3.69,4.00,4.00,NaN,NaN,NaN,NaN,NaN
25,20110018,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.33,146,01-AUG-20,2024-10-17,9,...,2.78,3.08,3.34,3.50,3.50,NaN,NaN,NaN,NaN,NaN
26,20110017,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.51,144,01-AUG-20,2024-10-17,9,...,3.44,2.98,3.57,3.20,3.50,NaN,NaN,NaN,NaN,NaN
27,20110016,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.83,146,01-AUG-20,2024-10-17,9,...,3.67,3.58,3.94,4.00,4.00,NaN,NaN,NaN,NaN,NaN
28,20110013,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.68,144,01-AUG-20,2024-02-02,7,...,3.60,3.93,3.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,20110012,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.73,146,01-AUG-20,2024-10-17,9,...,3.60,3.63,3.88,4.00,4.00,NaN,NaN,NaN,NaN,NaN
30,20110011,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.95,146,01-AUG-20,2024-10-17,9,...,3.85,3.92,4.00,4.00,4.00,NaN,NaN,NaN,NaN,NaN
31,20110009,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.24,155,01-AUG-20,2025-02-14,9,...,3.21,2.63,1.89,0.88,2.50,NaN,NaN,NaN,NaN,NaN
32,20110007,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.88,144,01-AUG-20,2024-10-17,9,...,3.63,3.80,3.85,4.00,3.50,NaN,NaN,NaN,NaN,NaN
33,20110005,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.53,156,01-AUG-20,2025-02-14,9,...,2.88,3.13,3.65,0.00,3.81,NaN,NaN,NaN,NaN,NaN
34,20110004,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.84,146,01-AUG-20,2024-02-02,7,...,3.85,3.67,3.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,20110003,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.90,145,01-AUG-20,2024-10-17,9,...,3.88,3.72,3.88,4.00,4.00,NaN,NaN,NaN,NaN,NaN
36,20110002,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.28,152,01-AUG-20,2025-02-14,9,...,3.02,3.40,2.67,0.00,3.00,NaN,NaN,NaN,NaN,NaN
37,20110001,SIK,S1SD-01-A,S1 Sains Data - Kampus Purwokerto,GRADUATED,3.51,145,01-AUG-20,2024-10-17,9,...,3.48,3.34,3.86,3.11,3.00,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
fitur = ['IPK Semester 1', 'IPK Semester 2', 'IPK Semester 3',
         'IPK Semester 4', 'IPK Semester 5', 'IPK Semester 6',
         'IPK Semester 7', 'SKS Lulus', 'IPK']
target = 'Total Semester'

In [ ]:
df_model = df[fitur + [target]].copy()
df_model = df_model.apply(pd.to_numeric, errors='coerce')

In [ ]:
df_model.fillna(-1, inplace=True)

In [ ]:
X = df_model[fitur]
y = df_model[target]

In [ ]:
df_model

,IPK Semester 1,IPK Semester 2,IPK Semester 3,IPK Semester 4,IPK Semester 5,IPK Semester 6,IPK Semester 7,SKS Lulus,IPK,Total Semester
0,3.63,3.45,3.41,3.540,3.43,3.85,3.68,148,3.57,7
1,3.92,3.55,3.85,3.850,3.83,3.92,3.82,147,3.82,7
2,4.00,3.75,3.50,3.810,3.76,3.68,3.65,153,3.70,7
3,3.84,3.61,3.77,3.850,3.93,3.82,3.85,153,3.81,7
4,4.00,3.30,3.50,3.670,3.85,3.85,3.87,151,3.72,7
5,3.84,3.60,3.40,3.910,3.87,3.74,3.68,144,3.72,7
6,3.76,3.64,3.67,3.830,3.96,3.95,3.65,147,3.78,7
7,3.87,3.20,3.44,3.690,3.73,3.83,3.65,147,3.63,7
8,3.82,3.50,3.36,3.750,3.23,3.65,3.75,148,3.58,7
9,3.95,3.99,3.69,3.940,3.93,3.98,3.68,147,3.88,7
10,4.00,4.00,3.98,4.000,3.93,4.00,3.91,151,3.98,7
11,3.89,3.77,3.85,3.940,3.87,3.85,3.78,151,3.85,7
12,3.66,3.66,3.54,3.730,3.74,3.87,3.75,150,3.70,7
13,3.84,3.84,3.88,4.000,3.93,4.00,3.85,148,3.90,7
14,4.00,3.98,3.90,4.000,4.00,4.00,3.91,150,3.97,7
15,3.45,3.30,3.67,3.690,3.71,3.67,3.54,146,3.60,9
16,3.66,3.93,3.83,3.880,3.88,3.98,4.00,145,3.87,7
17,3.47,3.25,3.63,4.000,3.37,3.18,3.73,154,3.55,9
18,3.34,3.73,3.67,2.330,3.20,3.26,3.88,146,3.49,9
19,3.16,3.08,3.15,4.000,2.88,2.13,2.81,147,2.93,9
20,3.89,3.80,3.93,3.630,3.75,3.98,3.31,145,3.81,9
21,3.84,4.00,4.00,3.830,3.76,3.70,3.88,144,3.89,9
22,3.55,3.43,3.61,4.000,3.50,3.28,3.79,146,3.57,9
23,3.92,3.88,4.00,3.915,3.83,3.43,4.00,146,3.90,9
24,3.74,4.00,4.00,3.730,3.59,3.90,3.69,145,3.85,9
25,3.39,3.38,3.48,3.520,2.78,3.08,3.34,146,3.33,9
26,3.37,3.38,3.72,4.000,3.44,2.98,3.57,144,3.51,9
27,3.74,3.78,3.87,3.890,3.67,3.58,3.94,146,3.83,9
28,3.42,3.55,3.33,3.760,3.60,3.93,3.79,144,3.68,7
29,3.61,3.70,3.93,3.220,3.60,3.63,3.88,146,3.73,9
30,4.00,3.93,4.00,3.850,3.85,3.92,4.00,146,3.95,9
31,2.95,3.33,3.50,4.000,3.21,2.63,1.89,155,3.24,9
32,4.00,4.00,3.87,4.000,3.63,3.80,3.85,144,3.88,9
33,3.34,3.23,2.87,4.000,2.88,3.13,3.65,156,3.53,9
34,3.76,3.85,3.91,4.000,3.85,3.67,3.80,146,3.84,7
35,4.00,3.93,3.93,3.905,3.88,3.72,3.88,145,3.90,9
36,3.08,3.20,3.50,4.000,3.02,3.40,2.67,152,3.28,9
37,3.58,3.73,3.43,4.000,3.48,3.34,3.86,145,3.51,9

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [ ]:
print("Koefisien regresi:", model.coef_)
print("Intercept:", model.intercept_)
print("Mean Squared Error:", mse)
print("R-squared (R²):", r2)

Koefisien regresi: [-0.26045763 -0.45417193  2.90344286 -0.06357938 -1.05769851 -1.38769173
 -0.13678919 -0.10797797  0.22401015]
Intercept: 24.620080102771947
Mean Squared Error: 1.113861385261202
R-squared (R²): -0.18811881094528227

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [ ]:
y_pred_rf = rf_model.predict(X_test)

In [ ]:
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

In [ ]:
print("Mean Squared Error (Random Forest):", mse_rf)
print("R-squared (Random Forest):", r2_rf)

Mean Squared Error (Random Forest): 0.18304999999999993
R-squared (Random Forest): 0.8047466666666667